In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
import glob
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

In [4]:
labels = pd.read_csv('self_assessments.csv', header=0, sep=';',)

In [6]:
labels.head()

,Tasks,hh2e,wfsl,37ir,hvpa,ql3b,r0a3,qx2o,wssm,ctzy,...,y8c3,g7r2,f6q3,e5p4,d4n6,c3m7,b2l8,a1k9,t6v9,b9w0
0,Breathing_relax,6,6,9,9,10,10,9,8,9,...,9,8,9,10,5,4,8,7,5,8
1,Breathing_stress,5,4,2,1,1,0,2,0,0,...,1,0,1,3,2,6,1,5,5,2
2,Breathing_valence,NaN,8,5,7,5,8,8,6,7,...,5,7,7,8,5,8,7,6,6,7
3,Breathing_arousal,NaN,3,3,8,2,1,2,1,7,...,7,5,1,3,4,7,8,8,3,8
4,Video1_relax,8,6,3,7,10,10,9,5,4,...,8,8,9,8,2,2,2,7,7,5

# Simple rule labels
#### Relax, valence and arousal

In [8]:
#path_data = "Dataset/Physiological/"
path_data = "/Users/havachaptoukaev/Desktop/PhD/All projects/2 - Stress Wearables/StressID Dataset/Physiological/"
path_save = ""

In [9]:
filelist= [f for f_sub in [f_names for root,d_names,f_names in os.walk(path_data)] for f in f_sub]
print("Should be :", 65*12 , ", there is:", len(filelist))
names = []
labs_binary = []
labs = []

Should be : 780 , there is: 792

In [10]:
filelist.sort()

In [11]:
lab_relax = []
lab_valence = []
lab_arousal = []

In [12]:
#### RELAX
for f in filelist:
     if not f.startswith('.'):
        split = f.split('_')
        subject = split[0]
        task = split[1].split('.')[0]
        
        if not task == 'Baseline':
            task_stress = task+'_relax'
            ans = labels[subject].loc[labels['Tasks'] == task_stress]
            names.append(subject+'_'+task)
            if not ans.isnull().all():
                #print('--')
                ans = int(ans)
                l_b =  0 if ans < 6 else 1  #[0-5][6-10]
                lab_relax.append(l_b)
        #print("------------")

In [13]:
#### VALENCE
for f in filelist:
     if not f.startswith('.'):
        split = f.split('_')
        subject = split[0]
        task = split[1].split('.')[0]
        
        if not task == 'Baseline':
            task_stress = task+'_valence'
            ans = labels[subject].loc[labels['Tasks'] == task_stress]
            
            if not ans.isnull().all():
                #print('--')
                ans = int(ans)
                l_b =  0 if ans < 6 else 1  #[0-5][6-10]
                lab_valence.append(l_b)
                
            else:
                lab_valence.append(np.nan)
        #print("------------")

In [14]:
#### AROUSAL
for f in filelist:
     if not f.startswith('.'):
        split = f.split('_')
        subject = split[0]
        task = split[1].split('.')[0]
        
        if not task == 'Baseline':
            task_stress = task+'_arousal'
            ans = labels[subject].loc[labels['Tasks'] == task_stress]
            
            if not ans.isnull().all():
                #print('--')
                ans = int(ans)
                l_b =  0 if ans < 6 else 1  #[0-5][6-10]
                lab_arousal.append(l_b)
                
            else:
                lab_arousal.append(np.nan)
        #print("------------")

### Export

In [15]:
df = {'subject/task':names, 'binary-relax': lab_relax, 'binary-valence': lab_valence, 'binary-arousal': lab_arousal}
labels_export = pd.DataFrame(df)
labels_export

       subject/task  binary-relax  binary-valence  binary-arousal
0    2ea4_Breathing             1             0.0             0.0
1    2ea4_Counting1             0             0.0             1.0
2    2ea4_Counting2             0             0.0             1.0
3    2ea4_Counting3             0             0.0             1.0
4         2ea4_Math             1             0.0             1.0
..              ...           ...             ...             ...
705      y9z6_Relax             1             1.0             0.0
706   y9z6_Speaking             0             0.0             1.0
707     y9z6_Stroop             0             1.0             1.0
708     y9z6_Video1             0             0.0             1.0
709     y9z6_Video2             0             0.0             0.0

[710 rows x 4 columns]

In [16]:
print("Should be :", 65*11 , ", there is:", labels_export.shape[0])

Should be : 715 , there is: 710

In [17]:
print("Binary split on relax")
labels_export['binary-relax'].value_counts()

Binary split on relax

binary-relax
0    384
1    326
Name: count, dtype: int64

In [18]:
print("Binary split on valence")
labels_export['binary-valence'].value_counts()

Binary split on valence

binary-valence
0.0    355
1.0    345
Name: count, dtype: int64

In [19]:
print("Binary split on arousal")
labels_export['binary-arousal'].value_counts()

Binary split on arousal

binary-arousal
1.0    501
0.0    199
Name: count, dtype: int64

In [20]:
labels_export.to_csv(path_save+'labels_supplementary.csv', index=False, sep=',')

In [21]:
for f in filelist:
     if not f.startswith('.'):
        split = f.split('_')
        subject = split[0]
        task = split[1].split('.')[0]
        
        if not task == 'Baseline':
            task_stress = task+'_stress'
            ans = labels[subject].loc[labels['Tasks'] == task_stress]
            
            if not ans.isnull().all():
                #print('--')
                ans = int(ans)
                l_b =  0 if ans < 5 else 1  #[0-5][6-10]
                #l = 0 if ans < 5 else 2 if ans > 7 else 1 #[0-4][5-7][8-10]

                names.append(subject+'_'+task)
                labs_binary.append(l_b)
                #labs.append(l)
                
        #print("------------")

# Binary stress and Elaborate rule

In [24]:
names = []
labs_binary = []
labs_3=[]
labs_3b=[]

In [ ]:
for f in filelist:
     if (not f.startswith('.') and 'hh2e' not in f):
        split = f.split('_')
        subject = split[0]
        task = split[1].split('.')[0]
        
        if not task == 'Baseline':
            stress = int(labels[subject].loc[labels['Tasks'] == task+'_stress'])
            relax = int(labels[subject].loc[labels['Tasks'] == task+'_relax'])
            arousal = int(labels[subject].loc[labels['Tasks'] == task+'_arousal'])
            valence = int(labels[subject].loc[labels['Tasks'] == task+'_valence'])
            
            """
            # BINARY : Not stressed - Stressed
            if ((valence < 5 and arousal > 5 and stress > 5) or (stress >=7 and relax < 5)):   #stress
                lb = 1
            elif((valence > 5 and arousal < 5 and relax > 5) or (relax >= 7 and stress < 5)): 
                lb = 0  #no stress
            
            """   
            
            # BINARY STRESS
            l_b =  0 if stress < 5 else 1


            # THREE CLASS (paper version): Relaxed - Neutral - Stressed
            if (valence < 5 and arousal > 5 and stress > 5):  #stress
                l3 = 2
            elif (valence >= 5 and arousal <= 5 and relax >= 5): #relaxed
                l3 = 0  #relax
            else:
                l3 = 1 #neutral
                
            # THREE CLASS V2 (refined to give more importance to strong statements): Relaxed - Neutral - Stressed
            if ((valence < 5 and arousal > 5 and stress > 5) or stress >=7):  #stress
                l3b = 2
            elif ((valence >= 5 and arousal <= 5 and relax >= 5) or relax >= 7): #relaxed
                l3b = 0  #relax
            else:
                l3b = 1 #neutral
                
            
            """
            # 4 CLASS : Not stress - Neutral - Mild stress -  Acute stress
            if ((valence >= 5 and arousal <= 5 and relax > 5) or relax >=7): 
                l4= 0  #relax
            elif ((valence <= 5 and arousal > 5 and stress > 5) or stress >=8):   #acute stress
                l4 = 3
            elif stress > 5: 
                l4 = 2
            else :
                l4 = 1 #neutral
            """
            
            names.append(subject+'_'+task)
            labs_binary.append(l_b)
            labs_3.append(l3)
            labs_3b.append(l3b)

# Export

In [28]:
df2 = {'subject/task':names, 'binary-stress':labs_binary,'affect3-class':labs_3, 'affect3-class-v2':labs_3b}
labels_export2 = pd.DataFrame(df2)
labels_export2

       subject/task  binary-stress  affect3-class  affect3-class-v2
0    2ea4_Breathing              0              0                 0
1    2ea4_Counting1              1              1                 2
2    2ea4_Counting2              1              1                 1
3    2ea4_Counting3              1              1                 1
4         2ea4_Math              1              1                 1
..              ...            ...            ...               ...
695      y9z6_Relax              0              0                 0
696   y9z6_Speaking              1              2                 2
697     y9z6_Stroop              1              1                 1
698     y9z6_Video1              1              1                 1
699     y9z6_Video2              0              1                 1

[700 rows x 4 columns]

In [29]:
print("Binary split on stress")
labels_export2['binary-stress'].value_counts()

Binary split on stress

binary-stress
1    368
0    332
Name: count, dtype: int64

In [30]:
print("3 class split on stress")
labels_export2['affect3-class'].value_counts()

3 class split on stress

affect3-class
1    470
0    138
2     92
Name: count, dtype: int64

In [31]:
print("3 class split on stress")
labels_export2['affect3-class-v2'].value_counts()

3 class split on stress

affect3-class-v2
0    257
1    242
2    201
Name: count, dtype: int64

In [32]:
labels_export2.to_csv(path_save+'labels.csv', index=False, sep=',')